
author: Vincenzo
title: "La Tua Azienda"
description: "Diffusione del Vangelo attraverso la tecnologia mobile."
baseurl: "" # Cambia se ospitato in una sottocartella
url: "https://amegicas.com" # Cambia con il tuo dominio
permalink: pretty

